### ISSUE TITLE
Pip failed

### ISSUE THREAD

**Issue by bio-unach** [BackofenLab/Acr#1]
Hello. great tool!

I have a problem installing. When conda runs, ends like this:

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch==1.8.0+cpu (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.8.0+cpu

CondaEnvException: Pip failed

**Comment by amri2k** [comment]
Thank you for your interest. We are working on the new update and hopefully will be online by next week and will take care of this issue.

Best, Omer
